/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import Controle.ConexaoBD;
import Controle.ControleMedico;
import Controle.ControlePaciente;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.TransferHandler;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author OSHIKURU
 */
public class CadastrarPacientes extends javax.swing.JInternalFrame {
    
    ConexaoBD conex = new ConexaoBD();//instânciando a classe ConexaoBD
    /**
     * Creates new form CadastrarMedico
     */
    public CadastrarPacientes() {
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) jTablePacientes.getModel();
        jTablePacientes.setRowSorter(new TableRowSorter(modelo));
        readJTablePacientes();
    }

    public void readJTablePacientes(){
        DefaultTableModel modelo = (DefaultTableModel) jTablePacientes.getModel();
       modelo.setNumRows(0);
        ControlePaciente dao = new ControlePaciente();
        
        for(Paciente P: dao.read()){
            
            modelo.addRow(new Object[]{
            
                P.getNumeroLivroMedico(),
                P.getNome(),
                P.getBi(),
                P.getDataNascimento(),
                P.getSexo(),
                
            
            });
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalMedicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomeDoPaciente = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButtonInserir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeDoPaciente1 = new javax.swing.JLabel();
        jLabelNomeDoPaciente2 = new javax.swing.JLabel();
        jTextFieldBi = new javax.swing.JTextField();
        jTextFieldNascimento = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro De Pacientes");

        jPanelPrincipalMedicos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipalMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("CADASTRAR PACIENTES");
        jPanelPrincipalMedicos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, 29));

        jLabelNomeDoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNomeDoPaciente.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeDoPaciente.setText("Nome:");
        jPanelPrincipalMedicos.add(jLabelNomeDoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 73, 38));

        jLabelSexo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 51, 0));
        jLabelSexo.setText("Sexo:");
        jPanelPrincipalMedicos.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 40, 48));
        jPanelPrincipalMedicos.add(jTextFieldNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 320, 40));

        jComboBoxSexo.setEditable(true);
        jComboBoxSexo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBoxSexo.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSexoActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 170, 52));

        jButtonInserir.setForeground(new java.awt.Color(255, 51, 0));
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 110, 40));

        jButtonExcluir.setForeground(new java.awt.Color(255, 51, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, 40));

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Do Livro Medico", "Nome", "Data De Nascimento", "B.I", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jPanelPrincipalMedicos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 770, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Idea_96px.png"))); // NOI18N
        jPanelPrincipalMedicos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, -1, 90));

        jLabelNomeDoPaciente1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNomeDoPaciente1.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeDoPaciente1.setText("Data De Nascimento:");
        jPanelPrincipalMedicos.add(jLabelNomeDoPaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 38));

        jLabelNomeDoPaciente2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNomeDoPaciente2.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeDoPaciente2.setText("B.I:");
        jPanelPrincipalMedicos.add(jLabelNomeDoPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 40, 30));
        jPanelPrincipalMedicos.add(jTextFieldBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 320, 40));
        jPanelPrincipalMedicos.add(jTextFieldNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        Paciente P = new Paciente();//Criando um objecto que vai receber os atributos da classe medico
        ControlePaciente dao = new ControlePaciente();//Criando um objecto que receber os atributos da variavel M e guardar na BD
        
       
       P.setNome(jTextFieldNomePaciente.getText());
       P.setBi(jTextFieldBi.getText());
       P.setDataNascimento(jTextFieldNascimento.getText());
       P.setSexo(jComboBoxSexo.getSelectedItem().toString());
       dao.create(P);
       
       
       jTextFieldNomePaciente.setText("");
       jTextFieldBi.setText("");
       jTextFieldNascimento.setText("");

       
        
                
        readJTablePacientes();
      
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
      
        ((DefaultTableModel) jTablePacientes.getModel()).removeRow(jTablePacientes.getSelectedRow());
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jComboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSexoActionPerformed
      
    }//GEN-LAST:event_jComboBoxSexoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNomeDoPaciente;
    private javax.swing.JLabel jLabelNomeDoPaciente1;
    private javax.swing.JLabel jLabelNomeDoPaciente2;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JPanel jPanelPrincipalMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldBi;
    private javax.swing.JTextField jTextFieldNascimento;
    private javax.swing.JTextField jTextFieldNomePaciente;
    // End of variables declaration//GEN-END:variables
}
