/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import Controle.ConexaoBD;
import Controle.ControleMedico;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.TransferHandler;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author OSHIKURU
 */
public class CadastrarMedico extends javax.swing.JInternalFrame {
    
    
   ConexaoBD conex = new ConexaoBD();//instânciando a classe ConexaoBD
    
        
        
    public CadastrarMedico() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
        jTableMedicos.setRowSorter(new TableRowSorter(modelo));
        readJTableMedicos();
        
    }
    
     public void readJTableMedicos(){
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
       modelo.setNumRows(0);
        ControleMedico dao = new ControleMedico();
        
        for(Medico M: dao.read()){
            
            modelo.addRow(new Object[]{
            
                M.getNumeroMedicos(),
                M.getNome(),
                M.getEspecialidade(),
                
            
            });
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalMedicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNomeDoMedico = new javax.swing.JLabel();
        jLabelEspecialidadeDoMedico = new javax.swing.JLabel();
        jTextFieldNomeMedico = new javax.swing.JTextField();
        jComboBoxEspecialidadeMedico = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro De Medicos");

        jPanelPrincipalMedicos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipalMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("CADASTRAR MEDICOS");
        jPanelPrincipalMedicos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 270, 29));

        jLabelNomeDoMedico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNomeDoMedico.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeDoMedico.setText("Nome:");
        jPanelPrincipalMedicos.add(jLabelNomeDoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 73, 38));

        jLabelEspecialidadeDoMedico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEspecialidadeDoMedico.setForeground(new java.awt.Color(255, 51, 0));
        jLabelEspecialidadeDoMedico.setText("Especialidade:");
        jPanelPrincipalMedicos.add(jLabelEspecialidadeDoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 89, 48));
        jPanelPrincipalMedicos.add(jTextFieldNomeMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 380, 38));

        jComboBoxEspecialidadeMedico.setEditable(true);
        jComboBoxEspecialidadeMedico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBoxEspecialidadeMedico.setForeground(new java.awt.Color(51, 51, 51));
        jComboBoxEspecialidadeMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Neurólogo", "MGI", "Cardiologo", "Dermatólogo", "Cirurgião", "Pediatra" }));
        jComboBoxEspecialidadeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialidadeMedicoActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jComboBoxEspecialidadeMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 380, 40));

        jButtonSalvar.setForeground(new java.awt.Color(255, 51, 0));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 110, 40));

        jButtonExcluir.setForeground(new java.awt.Color(255, 51, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, 40));

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codico", "Nome", "Especialidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jPanelPrincipalMedicos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 770, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Handshake_96px.png"))); // NOI18N
        jPanelPrincipalMedicos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        ((DefaultTableModel) jTableMedicos.getModel()).removeRow(jTableMedicos.getSelectedRow());//*Apagar os dados da tabela*//
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        Medico M = new Medico();//Criando um objecto que vai receber os atributos da classe medico
        ControleMedico dao = new ControleMedico();//Criando um objecto que receber os atributos da variavel M e guardar na BD
        
       
       M.setNome(jTextFieldNomeMedico.getText());
       M.setEspecialidade(jComboBoxEspecialidadeMedico.getSelectedItem().toString());
       dao.create(M);
       
       
       jTextFieldNomeMedico.setText("");
       
        
                
        readJTableMedicos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxEspecialidadeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialidadeMedicoActionPerformed

    }//GEN-LAST:event_jComboBoxEspecialidadeMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxEspecialidadeMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEspecialidadeDoMedico;
    private javax.swing.JLabel jLabelNomeDoMedico;
    private javax.swing.JPanel jPanelPrincipalMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextFieldNomeMedico;
    // End of variables declaration//GEN-END:variables
}
