/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.TransferHandler;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author OSHIKURU
 */
public class CadastrarConsulta extends javax.swing.JInternalFrame {
        ArrayList<Consulta> listaConsulta;
        
         public void carregarjTableConsulta(){
        DefaultTableModel dados = new DefaultTableModel(new Object[]{"Data Da Consulta", "Info Medico", "Info Paciente"},0);

        
        for(int k=0; k<listaConsulta.size(); k++){
            dados.addRow(new Object[]{listaConsulta.get(k).getDataConsulta(),listaConsulta.get(k).getInformaçãoMedico(),listaConsulta.get(k).getInformaçãoPaciente()});
        
        }
        jTableConsulta.setModel(dados);
    }
    /**
     * Creates new form CadastrarMedico
     */
    public CadastrarConsulta() {
        initComponents();
        listaConsulta = new ArrayList();
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalMedicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigoDoMedico = new javax.swing.JLabel();
        jLabelNomeDoMedico = new javax.swing.JLabel();
        jLabelEspecialidadeDoMedico = new javax.swing.JLabel();
        jTextFieldinfoPaciente = new javax.swing.JTextField();
        jTextFieldInfoMedico = new javax.swing.JTextField();
        jButtonInserir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro De Consultas");

        jPanelPrincipalMedicos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipalMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("CADASTRAR CONSULTA");
        jPanelPrincipalMedicos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 300, 29));

        jLabelCodigoDoMedico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCodigoDoMedico.setForeground(new java.awt.Color(255, 51, 0));
        jLabelCodigoDoMedico.setText("Data Da Consulta:");
        jPanelPrincipalMedicos.add(jLabelCodigoDoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 150, 120, 41));

        jLabelNomeDoMedico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelNomeDoMedico.setForeground(new java.awt.Color(255, 51, 0));
        jLabelNomeDoMedico.setText("Infromação do Medico:");
        jPanelPrincipalMedicos.add(jLabelNomeDoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 38));

        jLabelEspecialidadeDoMedico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEspecialidadeDoMedico.setForeground(new java.awt.Color(255, 51, 0));
        jLabelEspecialidadeDoMedico.setText("Informação Do Paciente:");
        jPanelPrincipalMedicos.add(jLabelEspecialidadeDoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 150, 48));
        jPanelPrincipalMedicos.add(jTextFieldinfoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 230, 39));
        jPanelPrincipalMedicos.add(jTextFieldInfoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 330, 38));

        jButtonInserir.setForeground(new java.awt.Color(255, 51, 0));
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, 40));

        jButtonExcluir.setForeground(new java.awt.Color(255, 51, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelPrincipalMedicos.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, 40));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Da Consulta", "Info Medico", "Info Paciente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jPanelPrincipalMedicos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 770, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Today_96px.png"))); // NOI18N
        jPanelPrincipalMedicos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 90));
        jPanelPrincipalMedicos.add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        ((DefaultTableModel) jTableConsulta.getModel()).removeRow(jTableConsulta.getSelectedRow());
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed

       //Receber os dados digitados no campo de texto e guardar em uma outra variavel
        String data = jFormattedTextFieldData.getText();
        int infoMedico = Integer.parseInt(jTextFieldInfoMedico.getText());
        int infoPaciente = Integer.parseInt(jTextFieldinfoPaciente.getText());
        
        
        //Criando um objecto para guardar os dados digitados
        Consulta consulta = new Consulta(data,infoMedico,infoPaciente);
        
        jFormattedTextFieldData.setText("");
        jTextFieldinfoPaciente.setText("");
        jTextFieldInfoMedico.setText("");
        

        jFormattedTextFieldData.requestFocus();
        
        //adicionar os dados do campo de texto, e adicionando a lista de Medico
        listaConsulta.add(consulta);
        carregarjTableConsulta();//Carregar a Tabela de Consulta
    }//GEN-LAST:event_jButtonInserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCodigoDoMedico;
    private javax.swing.JLabel jLabelEspecialidadeDoMedico;
    private javax.swing.JLabel jLabelNomeDoMedico;
    private javax.swing.JPanel jPanelPrincipalMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextField jTextFieldInfoMedico;
    private javax.swing.JTextField jTextFieldinfoPaciente;
    // End of variables declaration//GEN-END:variables
}
