/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import Controle.ConexaoBD;
import Controle.ControleMedico;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.TransferHandler;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author OSHIKURU
 */
public class ListaMedico extends javax.swing.JInternalFrame {
   ConexaoBD conex = new ConexaoBD();//instânciando a classe ConexaoBD
     
    
   

    /**
     * Creates new form CadastrarMedico
     */
    public ListaMedico() {
        initComponents();
       initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
        jTableMedicos.setRowSorter(new TableRowSorter(modelo));
        readJTableMedicos();
    }
    
    //Criando uma função para carregar a lista de Medicos e guardando em uma Tabela
    public void readJTableMedicos(){
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
       modelo.setNumRows(0);
        ControleMedico dao = new ControleMedico();
        
        for(Medico M: dao.read()){
            
            modelo.addRow(new Object[]{
            
                M.getNumeroMedicos(),
                M.getNome(),
                M.getEspecialidade(),
                
            
            });
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipalMedicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Lista De Medicos");

        jPanelPrincipalMedicos.setBackground(new java.awt.Color(204, 204, 255));
        jPanelPrincipalMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("LISTA DE MEDICOS");
        jPanelPrincipalMedicos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 270, 29));

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codico", "Nome", "Especialidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jPanelPrincipalMedicos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 770, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Clock_96px.png"))); // NOI18N
        jPanelPrincipalMedicos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 6, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipalMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelPrincipalMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    // End of variables declaration//GEN-END:variables

   
}
