/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import Controle.ConexaoBD;

/**
 *
 * @author OSHIKURU
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    
    ConexaoBD conecta = new ConexaoBD();
            
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jPanelMenuPrincipal = new javax.swing.JPanel();
        jpMenuListaDeMedicos = new javax.swing.JLabel();
        jpMenuListaDePacientes = new javax.swing.JLabel();
        jpMenuCadastrarPacientes = new javax.swing.JLabel();
        jpMenuListaDeConsultas = new javax.swing.JLabel();
        jpMenuCadastrarMedico = new javax.swing.JLabel();
        jLabelListaDeMedicos = new javax.swing.JLabel();
        jLabelListaDePacientes = new javax.swing.JLabel();
        JlCadastrarMedico = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JlCadastrarPacientes = new javax.swing.JLabel();
        jpMenuCadastrarConsultas = new javax.swing.JLabel();
        JlabelCadastrarConsultas = new javax.swing.JLabel();
        JlabelMenu_Principal = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuMedico = new javax.swing.JMenu();
        jMenuItemCadastrarMedicos = new javax.swing.JMenuItem();
        jMenuItemListaDeMedico = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenu();
        jMenuItemCadastrarPacientes = new javax.swing.JMenuItem();
        jMenuItemListaDePacientes = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConsulta = new javax.swing.JMenuItem();
        jMenuItemListaDeConsultas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE GESTÃO HOSPITALAR");

        jDesktopPanePrincipal.setBackground(new java.awt.Color(102, 255, 204));

        jPanelMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMenuPrincipal.setToolTipText("");
        jPanelMenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenuListaDeMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuListaDeMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Clock_96px.png"))); // NOI18N
        jpMenuListaDeMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuListaDeMedicosMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jpMenuListaDeMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 170, 80));

        jpMenuListaDePacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuListaDePacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Maintenance_96px.png"))); // NOI18N
        jpMenuListaDePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuListaDePacientesMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jpMenuListaDePacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 160, 100));

        jpMenuCadastrarPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuCadastrarPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Idea_96px.png"))); // NOI18N
        jpMenuCadastrarPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCadastrarPacientesMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jpMenuCadastrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 170, 100));

        jpMenuListaDeConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuListaDeConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Google_Drive_96px.png"))); // NOI18N
        jPanelMenuPrincipal.add(jpMenuListaDeConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 170, 100));

        jpMenuCadastrarMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuCadastrarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Handshake_96px.png"))); // NOI18N
        jpMenuCadastrarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCadastrarMedicoMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jpMenuCadastrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, 100));

        jLabelListaDeMedicos.setBackground(new java.awt.Color(240, 89, 61));
        jLabelListaDeMedicos.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        jLabelListaDeMedicos.setForeground(new java.awt.Color(240, 89, 61));
        jLabelListaDeMedicos.setText("Lista De Medico");
        jLabelListaDeMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListaDeMedicosMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jLabelListaDeMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, 40));

        jLabelListaDePacientes.setBackground(new java.awt.Color(240, 89, 61));
        jLabelListaDePacientes.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        jLabelListaDePacientes.setForeground(new java.awt.Color(240, 89, 61));
        jLabelListaDePacientes.setText("Lista De Pacientes");
        jLabelListaDePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListaDePacientesMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jLabelListaDePacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 140, 40));

        JlCadastrarMedico.setBackground(new java.awt.Color(240, 89, 61));
        JlCadastrarMedico.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        JlCadastrarMedico.setForeground(new java.awt.Color(240, 89, 61));
        JlCadastrarMedico.setText("Cadastrar Medico");
        JlCadastrarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCadastrarMedicoMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(JlCadastrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, 40));

        jLabel11.setBackground(new java.awt.Color(240, 89, 61));
        jLabel11.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 89, 61));
        jLabel11.setText("Lista de consultas Marcadas");
        jPanelMenuPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 200, 40));

        JlCadastrarPacientes.setBackground(new java.awt.Color(240, 89, 61));
        JlCadastrarPacientes.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        JlCadastrarPacientes.setForeground(new java.awt.Color(240, 89, 61));
        JlCadastrarPacientes.setText("Cadastrar Pacientes");
        JlCadastrarPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCadastrarPacientesMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(JlCadastrarPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, 40));

        jpMenuCadastrarConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenuCadastrarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Today_96px.png"))); // NOI18N
        jpMenuCadastrarConsultas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenuCadastrarConsultasMouseMoved(evt);
            }
        });
        jpMenuCadastrarConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCadastrarConsultasMouseClicked(evt);
            }
        });
        jPanelMenuPrincipal.add(jpMenuCadastrarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 170, 70));

        JlabelCadastrarConsultas.setBackground(new java.awt.Color(240, 89, 61));
        JlabelCadastrarConsultas.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        JlabelCadastrarConsultas.setForeground(new java.awt.Color(240, 89, 61));
        JlabelCadastrarConsultas.setText("Cadastrar Consulta");
        JlabelCadastrarConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelCadastrarConsultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JlabelCadastrarConsultasMouseEntered(evt);
            }
        });
        jPanelMenuPrincipal.add(JlabelCadastrarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 130, 30));

        JlabelMenu_Principal.setBackground(new java.awt.Color(240, 89, 61));
        JlabelMenu_Principal.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        JlabelMenu_Principal.setForeground(new java.awt.Color(240, 89, 61));
        JlabelMenu_Principal.setText("Menu Principal");
        JlabelMenu_Principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelMenu_PrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JlabelMenu_PrincipalMouseEntered(evt);
            }
        });
        jPanelMenuPrincipal.add(JlabelMenu_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 150, 30));

        jDesktopPanePrincipal.setLayer(jPanelMenuPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        jMenuBarPrincipal.setBackground(new java.awt.Color(204, 51, 0));
        jMenuBarPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jMenuMedico.setBackground(new java.awt.Color(204, 51, 0));
        jMenuMedico.setForeground(new java.awt.Color(255, 102, 0));
        jMenuMedico.setText("Medico");

        jMenuItemCadastrarMedicos.setText("Cadastrar Medico");
        jMenuItemCadastrarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarMedicosActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemCadastrarMedicos);

        jMenuItemListaDeMedico.setText("Lista De Medico");
        jMenuItemListaDeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaDeMedicoActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemListaDeMedico);

        jMenuBarPrincipal.add(jMenuMedico);

        jMenuPaciente.setForeground(new java.awt.Color(204, 102, 0));
        jMenuPaciente.setText("Paciente");

        jMenuItemCadastrarPacientes.setText("Cadastrar Pacientes");
        jMenuItemCadastrarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarPacientesActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemCadastrarPacientes);

        jMenuItemListaDePacientes.setText("Lista De Pacientes");
        jMenuItemListaDePacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaDePacientesActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemListaDePacientes);

        jMenuBarPrincipal.add(jMenuPaciente);

        jMenuConsultas.setForeground(new java.awt.Color(204, 102, 0));
        jMenuConsultas.setText("Consultas");

        jMenuItemConsulta.setText("Cadastrar Consulta");
        jMenuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsulta);

        jMenuItemListaDeConsultas.setText("Lista De Consultas");
        jMenuConsultas.add(jMenuItemListaDeConsultas);

        jMenuBarPrincipal.add(jMenuConsultas);

        jMenu1.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenu1);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(1008, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListaDePacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaDePacientesActionPerformed
        ListaPacientes listaPaciente = new ListaPacientes();
        jDesktopPanePrincipal.add(listaPaciente);
        listaPaciente.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaDePacientesActionPerformed

    private void jMenuItemCadastrarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarMedicosActionPerformed
        CadastrarMedico cadastrarMedico = new CadastrarMedico();
        jDesktopPanePrincipal.add(cadastrarMedico);
        cadastrarMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarMedicosActionPerformed

    private void jMenuItemListaDeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaDeMedicoActionPerformed
        ListaMedico listaMedico = new ListaMedico();
        jDesktopPanePrincipal.add(listaMedico);
        listaMedico.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaDeMedicoActionPerformed

    private void jMenuItemCadastrarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarPacientesActionPerformed
        CadastrarPacientes cadastrarPaciente = new CadastrarPacientes();
        jDesktopPanePrincipal.add(cadastrarPaciente);
        cadastrarPaciente.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastrarPacientesActionPerformed

    private void JlCadastrarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCadastrarMedicoMouseClicked

         CadastrarMedico cadastrarMedico = new CadastrarMedico();
        jDesktopPanePrincipal.add(cadastrarMedico);
        cadastrarMedico.setVisible(true);
    }//GEN-LAST:event_JlCadastrarMedicoMouseClicked

    private void JlCadastrarPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCadastrarPacientesMouseClicked
        CadastrarPacientes cadastrarPaciente = new CadastrarPacientes();
        jDesktopPanePrincipal.add(cadastrarPaciente);
        cadastrarPaciente.setVisible(true);
    }//GEN-LAST:event_JlCadastrarPacientesMouseClicked

    private void jpMenuCadastrarConsultasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCadastrarConsultasMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jpMenuCadastrarConsultasMouseMoved

    private void JlabelCadastrarConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelCadastrarConsultasMouseClicked
        CadastrarConsulta cadastrarConsulta = new CadastrarConsulta();
        jDesktopPanePrincipal.add(cadastrarConsulta);
        cadastrarConsulta.setVisible(true);
    }//GEN-LAST:event_JlabelCadastrarConsultasMouseClicked

    private void JlabelCadastrarConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelCadastrarConsultasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelCadastrarConsultasMouseEntered

    private void JlabelMenu_PrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelMenu_PrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelMenu_PrincipalMouseClicked

    private void JlabelMenu_PrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelMenu_PrincipalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JlabelMenu_PrincipalMouseEntered

    private void jpMenuCadastrarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCadastrarMedicoMouseClicked
        CadastrarMedico cadastrarMedico = new CadastrarMedico();
        jDesktopPanePrincipal.add(cadastrarMedico);
        cadastrarMedico.setVisible(true);
    }//GEN-LAST:event_jpMenuCadastrarMedicoMouseClicked

    private void jpMenuCadastrarPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCadastrarPacientesMouseClicked
         CadastrarPacientes cadastrarPaciente = new CadastrarPacientes();
        jDesktopPanePrincipal.add(cadastrarPaciente);
        cadastrarPaciente.setVisible(true);
    }//GEN-LAST:event_jpMenuCadastrarPacientesMouseClicked

    private void jMenuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaActionPerformed
        CadastrarConsulta cadastrarConsulta = new CadastrarConsulta();
        jDesktopPanePrincipal.add(cadastrarConsulta);
        cadastrarConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaActionPerformed

    private void jpMenuCadastrarConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCadastrarConsultasMouseClicked
        CadastrarConsulta cadastrarConsulta = new CadastrarConsulta();
        jDesktopPanePrincipal.add(cadastrarConsulta);
        cadastrarConsulta.setVisible(true);
    }//GEN-LAST:event_jpMenuCadastrarConsultasMouseClicked

    private void jpMenuListaDeMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuListaDeMedicosMouseClicked
        ListaMedico listaMedico = new ListaMedico();
        jDesktopPanePrincipal.add(listaMedico);
        listaMedico.setVisible(true);
    }//GEN-LAST:event_jpMenuListaDeMedicosMouseClicked

    private void jpMenuListaDePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuListaDePacientesMouseClicked
        ListaPacientes listaPaciente = new ListaPacientes();
        jDesktopPanePrincipal.add(listaPaciente);
        listaPaciente.setVisible(true);
    }//GEN-LAST:event_jpMenuListaDePacientesMouseClicked

    private void jLabelListaDeMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListaDeMedicosMouseClicked
        ListaMedico listaMedico = new ListaMedico();
        jDesktopPanePrincipal.add(listaMedico);
        listaMedico.setVisible(true);
    }//GEN-LAST:event_jLabelListaDeMedicosMouseClicked

    private void jLabelListaDePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListaDePacientesMouseClicked
        ListaPacientes listaPaciente = new ListaPacientes();
        jDesktopPanePrincipal.add(listaPaciente);
        listaPaciente.setVisible(true);
    }//GEN-LAST:event_jLabelListaDePacientesMouseClicked

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
        
       
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlCadastrarMedico;
    private javax.swing.JLabel JlCadastrarPacientes;
    private javax.swing.JLabel JlabelCadastrarConsultas;
    private javax.swing.JLabel JlabelMenu_Principal;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelListaDeMedicos;
    private javax.swing.JLabel jLabelListaDePacientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemCadastrarMedicos;
    private javax.swing.JMenuItem jMenuItemCadastrarPacientes;
    private javax.swing.JMenuItem jMenuItemConsulta;
    private javax.swing.JMenuItem jMenuItemListaDeConsultas;
    private javax.swing.JMenuItem jMenuItemListaDeMedico;
    private javax.swing.JMenuItem jMenuItemListaDePacientes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuMedico;
    private javax.swing.JMenu jMenuPaciente;
    private javax.swing.JPanel jPanelMenuPrincipal;
    private javax.swing.JLabel jpMenuCadastrarConsultas;
    private javax.swing.JLabel jpMenuCadastrarMedico;
    private javax.swing.JLabel jpMenuCadastrarPacientes;
    private javax.swing.JLabel jpMenuListaDeConsultas;
    private javax.swing.JLabel jpMenuListaDeMedicos;
    private javax.swing.JLabel jpMenuListaDePacientes;
    // End of variables declaration//GEN-END:variables
}
